### ISSUE TITLE
web_page_utils imports from cups, not listed as dependency

### ISSUE THREAD

**Issue by dleehr** [YoderLab/MMAP#2]
Attempting to run main.py results in a failure if the [cups](https://pypi.python.org/pypi/pycups) module is not present

```
$ python src/core/main.py /vagrant/control 
Traceback (most recent call last):
  File "src/core/main.py", line 25, in <module>
    from core.assembler.software_assembler import SoftwareAssembler
  File "/vagrant/MMAP/src/core/assembler/software_assembler.py", line 9, in <module>
    from core.component.run_BLAST import RunBlast
  File "/vagrant/MMAP/src/core/component/run_BLAST.py", line 13, in <module>
    from core.amigo.go_sequence import GoSequence
  File "/vagrant/MMAP/src/core/amigo/go_sequence.py", line 10, in <module>
    from core.amigo import web_page_utils
  File "/vagrant/MMAP/src/core/amigo/web_page_utils.py", line 12, in <module>
    from cups import HTTPError
ImportError: No module named cups
```

**Comment by dleehr** [comment]
CUPS is the Common Unix Printing System, and pycups is a python wrapper for it. I don't see a reason why it is imported

**Comment by stevenhwu** [comment]
I agree. cups is totally unnecessary and it should be removed. I have no idea how that got here, could be my stupid IDE.
